In [9]:
import pandas as pd

In [10]:
df = pd.read_csv('./data/인구순이동률2012-2022.csv')

In [11]:
df

,시점,전국,서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별자치시,경기도,강원특별자치도,충청북도,충청남도,전북특별자치도,전라남도,경상북도,경상남도,제주특별자치도
0,시점,순이동률(%),순이동률(%),순이동률(%),순이동률(%),순이동률(%),순이동률(%),순이동률(%),순이동률(%),순이동률(%),순이동률(%),순이동률(%),순이동률(%),순이동률(%),순이동률(%),순이동률(%),순이동률(%),순이동률(%),순이동률(%)
1,2022,0.0,-0.4,-0.4,-0.5,1.0,-0.5,-0.2,-0.9,2.7,0.3,0.5,0.3,0.7,-0.3,0.0,-0.3,-0.6,0.5
2,2021,0.0,-1.1,-0.6,-1.0,0.4,-0.4,-0.6,-1.2,3.9,1.1,0.4,0.2,0.4,-0.3,-0.2,0.1,-0.4,0.6
3,2020,0.0,-0.7,-0.4,-0.7,-0.5,-0.4,-0.8,-1.2,3.8,1.3,0.4,0.2,0.0,-0.5,-0.5,-0.6,-0.5,0.5
4,2019,0.0,-0.5,-0.7,-1.0,-0.1,-0.3,-1.1,-0.9,7.3,1.0,0.1,0.2,0.0,-0.7,-0.5,-0.2,-0.3,0.4
5,2018,0.0,-1.1,-0.8,-0.6,0.0,-0.4,-1.0,-1.1,10.6,1.3,-0.3,0.3,0.5,-0.8,-0.4,-0.3,-0.2,1.3
6,2017,0.0,-1.0,-0.8,-0.5,-0.1,-0.6,-1.1,-1.0,13.3,0.9,0.1,0.1,0.9,-0.4,-0.2,-0.2,0.1,2.2
7,2016,0.0,-1.4,-0.6,-0.4,0.2,-0.5,-0.7,-0.7,13.2,1.1,0.1,0.3,0.7,-0.2,-0.2,-0.1,0.1,2.3
8,2015,0.0,-1.4,-0.4,-0.5,0.3,-0.6,-1.4,0.0,29.0,0.8,0.3,0.1,0.5,-0.2,0.2,0.0,0.2,2.3
9,2014,0.0,-0.9,-0.4,-0.6,0.3,-0.2,-0.6,0.2,24.2,0.5,0.1,0.2,0.5,-0.1,0.0,0.0,0.2,1.9
10,2013,0.0,-1.0,-0.5,-0.5,0.8,-0.2,0.0,0.2,7.4,0.6,0.2,0.2,0.7,-0.1,-0.1,-0.1,0.1,1.3
11,2012,0.0,-1.0,-0.6,-0.4,1.0,-0.1,0.0,0.4,31.2,0.7,0.0,0.3,0.5,-0.2,-0.3,-0.2,-0.1,0.8

In [12]:
# 기존 열 이름 리스트 (시점 제외)
columns = ['전국', '서울특별시', '부산광역시', '대구광역시', '인천광역시', '광주광역시', '대전광역시', '울산광역시', '세종특별자치시', '경기도', '강원특별자치도', '충청북도', '충청남도', '전북특별자치도', '전라남도', '경상북도', '경상남도', '제주특별자치도']

# '순이동률(%)'에서 % 제거하고 '순이동률'만 붙이기
new_columns = [f"{col}" for col in columns]

# 데이터프레임 열 이름 변경 (예: df가 원본 데이터프레임)
df.columns = ['Year'] + new_columns

In [13]:
df = df.drop(index=0).reset_index(drop=True)  # 첫 번째(0번) 행 제거 후 인덱스 재정렬
df

,Year,전국,서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별자치시,경기도,강원특별자치도,충청북도,충청남도,전북특별자치도,전라남도,경상북도,경상남도,제주특별자치도
0,2022,0.0,-0.4,-0.4,-0.5,1.0,-0.5,-0.2,-0.9,2.7,0.3,0.5,0.3,0.7,-0.3,0.0,-0.3,-0.6,0.5
1,2021,0.0,-1.1,-0.6,-1.0,0.4,-0.4,-0.6,-1.2,3.9,1.1,0.4,0.2,0.4,-0.3,-0.2,0.1,-0.4,0.6
2,2020,0.0,-0.7,-0.4,-0.7,-0.5,-0.4,-0.8,-1.2,3.8,1.3,0.4,0.2,0.0,-0.5,-0.5,-0.6,-0.5,0.5
3,2019,0.0,-0.5,-0.7,-1.0,-0.1,-0.3,-1.1,-0.9,7.3,1.0,0.1,0.2,0.0,-0.7,-0.5,-0.2,-0.3,0.4
4,2018,0.0,-1.1,-0.8,-0.6,0.0,-0.4,-1.0,-1.1,10.6,1.3,-0.3,0.3,0.5,-0.8,-0.4,-0.3,-0.2,1.3
5,2017,0.0,-1.0,-0.8,-0.5,-0.1,-0.6,-1.1,-1.0,13.3,0.9,0.1,0.1,0.9,-0.4,-0.2,-0.2,0.1,2.2
6,2016,0.0,-1.4,-0.6,-0.4,0.2,-0.5,-0.7,-0.7,13.2,1.1,0.1,0.3,0.7,-0.2,-0.2,-0.1,0.1,2.3
7,2015,0.0,-1.4,-0.4,-0.5,0.3,-0.6,-1.4,0.0,29.0,0.8,0.3,0.1,0.5,-0.2,0.2,0.0,0.2,2.3
8,2014,0.0,-0.9,-0.4,-0.6,0.3,-0.2,-0.6,0.2,24.2,0.5,0.1,0.2,0.5,-0.1,0.0,0.0,0.2,1.9
9,2013,0.0,-1.0,-0.5,-0.5,0.8,-0.2,0.0,0.2,7.4,0.6,0.2,0.2,0.7,-0.1,-0.1,-0.1,0.1,1.3
10,2012,0.0,-1.0,-0.6,-0.4,1.0,-0.1,0.0,0.4,31.2,0.7,0.0,0.3,0.5,-0.2,-0.3,-0.2,-0.1,0.8

In [14]:
df_long = df.melt(id_vars='Year', var_name='지역', value_name='순이동률')

# 컬럼명 변경
df_long = df_long.rename(columns={'Year': '년도'})

# 연도, 지역, 순이동률 순서로 정렬
df_long = df_long[['년도', '지역', '순이동률']]

# 연도, 지역 기준 정렬
df_long = df_long.sort_values(['년도', '지역']).reset_index(drop=True)


df_long = df_long.rename(columns={'년도': 'Year'})
df_long = df_long.rename(columns={'지역': 'Region'})


display(df_long)

     Year   Region  순이동률
0    2012  강원특별자치도   0.0
1    2012      경기도   0.7
2    2012     경상남도  -0.1
3    2012     경상북도  -0.2
4    2012    광주광역시  -0.1
..    ...      ...   ...
193  2022     전라남도   0.0
194  2022  전북특별자치도  -0.3
195  2022  제주특별자치도   0.5
196  2022     충청남도   0.7
197  2022     충청북도   0.3

[198 rows x 3 columns]

In [15]:
# 지역 이름을 영어로 변환
region_map = {
    "전국" : "Whole country",
    "서울특별시": "Seoul",
    "부산광역시": "Busan",
    "대구광역시": "Daegu",
    "인천광역시": "Incheon",
    "광주광역시": "Gwangju",
    "대전광역시": "Daejeon",
    "울산광역시": "Ulsan",
    "세종특별자치시": "Sejong",
    "경기도": "Gyeonggi-do",
    "강원특별자치도": "Gangwon-do",
    "충청북도": "Chungcheongbuk-do",
    "충청남도": "Chungcheongnam-do",
    "전라북도": "Jeollabuk-do",
    "전라남도": "Jeollanam-do",
    "경상북도": "Gyeongsangbuk-do",
    "경상남도": "Gyeongsangnam-do",
    "제주특별자치도": "Jeju"
}

df_long["Region"] = df_long["Region"].map(region_map)



# 결과 출력
display(df_long.head(50))

# 저장
df_long.to_csv('./data/지역별순이동률2012-2022.csv',encoding='utf-8',index=False)

    Year             Region  순이동률
0   2012         Gangwon-do   0.0
1   2012        Gyeonggi-do   0.7
2   2012   Gyeongsangnam-do  -0.1
3   2012   Gyeongsangbuk-do  -0.2
4   2012            Gwangju  -0.1
5   2012              Daegu  -0.4
6   2012            Daejeon   0.0
7   2012              Busan  -0.6
8   2012              Seoul  -1.0
9   2012             Sejong  31.2
10  2012              Ulsan   0.4
11  2012            Incheon   1.0
12  2012      Whole country   0.0
13  2012       Jeollanam-do  -0.3
14  2012                NaN  -0.2
15  2012               Jeju   0.8
16  2012  Chungcheongnam-do   0.5
17  2012  Chungcheongbuk-do   0.3
18  2013         Gangwon-do   0.2
19  2013        Gyeonggi-do   0.6
20  2013   Gyeongsangnam-do   0.1
21  2013   Gyeongsangbuk-do  -0.1
22  2013            Gwangju  -0.2
23  2013              Daegu  -0.5
24  2013            Daejeon   0.0
25  2013              Busan  -0.5
26  2013              Seoul  -1.0
27  2013             Sejong   7.4
28  2013              Ulsan   0.2
29  2013            Incheon   0.8
30  2013      Whole country   0.0
31  2013       Jeollanam-do  -0.1
32  2013                NaN  -0.1
33  2013               Jeju   1.3
34  2013  Chungcheongnam-do   0.7
35  2013  Chungcheongbuk-do   0.2
36  2014         Gangwon-do   0.1
37  2014        Gyeonggi-do   0.5
38  2014   Gyeongsangnam-do   0.2
39  2014   Gyeongsangbuk-do   0.0
40  2014            Gwangju  -0.2
41  2014              Daegu  -0.6
42  2014            Daejeon  -0.6
43  2014              Busan  -0.4
44  2014              Seoul  -0.9
45  2014             Sejong  24.2
46  2014              Ulsan   0.2
47  2014            Incheon   0.3
48  2014      Whole country   0.0
49  2014       Jeollanam-do   0.0